import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-slist',
  templateUrl: './slist.component.html',
  styleUrls: ['./slist.component.css']
})
export class SlistComponent implements OnInit {

  plist: any;
  constructor() {
    this.plist = [
      {
        pid: 1,
        ptype: 'residencial',
        routerLink: ['/features'],
        rupee: ` ₹`,
        persqftrs: '69136',
        persqft: 'per sqft',
        text1: `for Sale in Greater Kailash`,
        budget: '28 crore',
        text3: 'Baashyaam Constructions',
        bhk: '6 BHK',
        cotegory: 'House',
        areatype: 'Super area',
        sqft: '450 sqyrd',
        furnishtype: 'Unfurnished',
        mstatus: 'Status',
        movestatus: 'Ready to Move',
        flooroutof: '4 out of 5',
        washroom: 'Washroom',
        noofwashroom: 2,
        floor: 'Floor',
        nooffloor: '5',
        agent: 'Agent',
        buyers: '+ Buyers Served',
        buyerslist: 520,
        agentname: ' Sudarshan Sharma',
        pdetails: `Freehold Residential House built over 3 floors is a great deal to invest in.`,
        cabtn: 'Contact Agent',
        pdbtn: `Property Detail's`,
        image: 'http://198.12.156.249:45001/pd/assets/images/propertylist/pg-11.jpg'
      },

      {
        pid: 2,
        ptype: 'residencial',
        routerLink: ['/features'],
        rupee: ` ₹`,
        persqftrs: '125000',
        persqft: 'per sqft',
        text1: `for sale in Golf Links`,
        budget: '50 crore',
        bhk: '5 BHK',
        cotegory: 'House',
        areatype: 'Super area',
        sqft: '4000 sqft',
        furnishtype: 'Unfurnished',
        mstatus: 'Status',
        movestatus: 'Ready to Move',
        flooroutof: '6 out of 8',
        washroom: 'Washroom',
        noofwashroom: 3,
        floor: 'Floor',
        nooffloor: '8',
        agent: 'Agent',
        buyers: '+ Buyers Served',
        buyerslist: 920,
        agentname: ' Aman Bajaj',
        pdetails: `Freehold Residential House faces North direction & is made upto 1 floor. `,
        cabtn: 'Contact Agent',
        pdbtn: `Property Detail's`,
        image: 'http://198.12.156.249:45001/pd/assets/images/propertylist/pg-10.jpg'
      },
      {
        pid: 3,
        ptype: 'residencial',
        routerLink: ['/features'],
        rupee: ` ₹`,
        persqftrs: '168350',
        persqft: 'per sqft',
        text1: `for sale in DJA Apartments, Sector 13 Dwarka`,
        budget: '25 crore',
        bhk: '3 BHK',
        cotegory: 'Penthouse',
        areatype: 'Super area',
        sqft: '1485 sqft',
        furnishtype: 'Unfurnished',
        mstatus: 'Status',
        movestatus: 'Ready to Move',
        flooroutof: '3 out of 4',
        washroom: 'Washroom',
        noofwashroom: 2,
        floor: 'Floor',
        nooffloor: '4',
        agent: 'Owner',
        buyers: '+ Buyers Served',
        buyerslist: 128,
        agentname: ' Ravi',
        pdetails: `Pent house is available for sale. It is fully furnished including 4 imported AC, fully loaded kitchen. `,
        cabtn: 'Contact Agent',
        pdbtn: `Property Detail's`,
        image: 'http://198.12.156.249:45001/pd/assets/images/propertylist/pg-6.jpg'
      },

      {
        pid: 4,
        ptype: 'residencial',
        routerLink: ['/features'],
        rupee: ` ₹`,
        persqftrs: '30625',
        persqft: 'per sqft',
        text1: `for sale in Vasant Vihar, New Delhi`,
        budget: '34 crore',
        bhk: '4 BHK',
        cotegory: 'Builder Floor',
        areatype: 'Super area',
        sqft: '8000 sqft',
        furnishtype: 'Unfurnished',
        mstatus: 'Status',
        movestatus: 'Ready to Move',
        flooroutof: 'Ground out of 4',
        washroom: 'Washroom',
        noofwashroom: 5,
        floor: 'Floor',
        nooffloor: '4',
        agent: 'Agent',
        buyers: '+ Buyers Served',
        buyerslist: 729,
        agentname: 'Miglani Enterprises',
        pdetails: `Luxurious Brand New Basement and Ground floor for sale in Vasant Vihar. `,
        cabtn: 'Contact Agent',
        pdbtn: `Property Detail's`,
        image: 'http://198.12.156.249:45001/pd/assets/images/propertylist/pg-7.jpg'
      },

      {
        pid: 5,
        ptype: 'residencial',
        routerLink: ['/features'],
        rupee: ` ₹`,
        persqftrs: '69136',
        persqft: 'per sqft',
        text1: `for Sale in Greater Kailash`,
        budget: '28 crore',
        text3: 'Baashyaam Constructions',
        bhk: '6 BHK',
        cotegory: 'House',
        areatype: 'Super area',
        sqft: '450 sqyrd',
        furnishtype: 'Unfurnished',
        mstatus: 'Status',
        movestatus: 'Ready to Move',
        flooroutof: '4 out of 5',
        washroom: 'Washroom',
        noofwashroom: 2,
        floor: 'Floor',
        nooffloor: '5',
        agent: 'Agent',
        buyers: '+ Buyers Served',
        buyerslist: 520,
        agentname: ' Sudarshan Sharma',
        pdetails: `Freehold Residential House built over 3 floors is a great deal to invest in.`,
        cabtn: 'Contact Agent',
        pdbtn: `Property Detail's`,
        image: 'http://198.12.156.249:45001/pd/assets/images/propertylist/pg-8.jpg'
      },

      {
        pid: 6,
        ptype: 'residencial',
        routerLink: ['/features'],
        rupee: ` ₹`,
        persqftrs: '125000',
        persqft: 'per sqft',
        text1: `for sale in Golf Links`,
        budget: '50 crore',
        bhk: '5 BHK',
        cotegory: 'House',
        areatype: 'Super area',
        sqft: '4000 sqft',
        furnishtype: 'Unfurnished',
        mstatus: 'Status',
        movestatus: 'Ready to Move',
        flooroutof: '6 out of 8',
        washroom: 'Washroom',
        noofwashroom: 3,
        floor: 'Floor',
        nooffloor: '8',
        agent: 'Agent',
        buyers: '+ Buyers Served',
        buyerslist: 920,
        agentname: ' Aman Bajaj',
        pdetails: `Freehold Residential House faces North direction & is made upto 1 floor. `,
        cabtn: 'Contact Agent',
        pdbtn: `Property Detail's`,
        image: 'http://198.12.156.249:45001/pd/assets/images/propertylist/pg-9.jpg'
      },
      {
        pid: 7,
        ptype: 'residencial',
        routerLink: ['/features'],
        rupee: ` ₹`,
        persqftrs: '168350',
        persqft: 'per sqft',
        text1: `for sale in DJA Apartments, Sector 13 Dwarka`,
        budget: '25 crore',
        bhk: '3 BHK',
        cotegory: 'Penthouse',
        areatype: 'Super area',
        sqft: '1485 sqft',
        furnishtype: 'Unfurnished',
        mstatus: 'Status',
        movestatus: 'Ready to Move',
        flooroutof: '3 out of 4',
        washroom: 'Washroom',
        noofwashroom: 2,
        floor: 'Floor',
        nooffloor: '4',
        agent: 'Owner',
        buyers: '+ Buyers Served',
        buyerslist: 128,
        agentname: ' Ravi',
        pdetails: `Pent house is available for sale. It is fully furnished including 4 imported AC, fully loaded kitchen. `,
        cabtn: 'Contact Agent',
        pdbtn: `Property Detail's`,
        image: 'http://198.12.156.249:45001/pd/assets/images/propertylist/pg-10.jpg'
      },

      {
        pid: 8,
        ptype: 'residencial',
        routerLink: ['/features'],
        rupee: ` ₹`,
        persqftrs: '30625',
        persqft: 'per sqft',
        text1: `for sale in Vasant Vihar, New Delhi`,
        budget: '34 crore',
        bhk: '4 BHK',
        cotegory: 'Builder Floor',
        areatype: 'Super area',
        sqft: '8000 sqft',
        furnishtype: 'Unfurnished',
        mstatus: 'Status',
        movestatus: 'Ready to Move',
        flooroutof: 'Ground out of 4',
        washroom: 'Washroom',
        noofwashroom: 5,
        floor: 'Floor',
        nooffloor: '4',
        agent: 'Agent',
        buyers: '+ Buyers Served',
        buyerslist: 729,
        agentname: 'Miglani Enterprises',
        pdetails: `Luxurious Brand New Basement and Ground floor for sale in Vasant Vihar. `,
        cabtn: 'Contact Agent',
        pdbtn: `Property Detail's`,
        image: 'http://198.12.156.249:45001/pd/assets/images/propertylist/pg-11.jpg'
      },



      {
        pid: 9,
        ptype: 'residencial',
        routerLink: ['/features'],
        rupee: ` ₹`,
        persqftrs: '69136',
        persqft: 'per sqft',
        text1: `for Sale in Greater Kailash`,
        budget: '28 crore',
        text3: 'Baashyaam Constructions',
        bhk: '6 BHK',
        cotegory: 'House',
        areatype: 'Super area',
        sqft: '450 sqyrd',
        furnishtype: 'Unfurnished',
        mstatus: 'Status',
        movestatus: 'Ready to Move',
        flooroutof: '4 out of 5',
        washroom: 'Washroom',
        noofwashroom: 2,
        floor: 'Floor',
        nooffloor: '5',
        agent: 'Agent',
        buyers: '+ Buyers Served',
        buyerslist: 520,
        agentname: ' Sudarshan Sharma',
        pdetails: `Freehold Residential House built over 3 floors is a great deal to invest in.`,
        cabtn: 'Contact Agent',
        pdbtn: `Property Detail's`,
        image: 'http://198.12.156.249:45001/pd/assets/images/propertylist/pg-4.jpg'
      },

      {
        pid: 10,
        ptype: 'residencial',
        routerLink: ['/features'],
        rupee: ` ₹`,
        persqftrs: '125000',
        persqft: 'per sqft',
        text1: `for sale in Golf Links`,
        budget: '50 crore',
        bhk: '5 BHK',
        cotegory: 'House',
        areatype: 'Super area',
        sqft: '4000 sqft',
        furnishtype: 'Unfurnished',
        mstatus: 'Status',
        movestatus: 'Ready to Move',
        flooroutof: '6 out of 8',
        washroom: 'Washroom',
        noofwashroom: 3,
        floor: 'Floor',
        nooffloor: '8',
        agent: 'Agent',
        buyers: '+ Buyers Served',
        buyerslist: 920,
        agentname: ' Aman Bajaj',
        pdetails: `Freehold Residential House faces North direction & is made upto 1 floor. `,
        cabtn: 'Contact Agent',
        pdbtn: `Property Detail's`,
        image: 'http://198.12.156.249:45001/pd/assets/images/propertylist/pg-5.jpg'
      },
      {
        pid: 11,
        ptype: 'residencial',
        routerLink: ['/features'],
        rupee: ` ₹`,
        persqftrs: '168350',
        persqft: 'per sqft',
        text1: `for sale in DJA Apartments, Sector 13 Dwarka`,
        budget: '25 crore',
        bhk: '3 BHK',
        cotegory: 'Penthouse',
        areatype: 'Super area',
        sqft: '1485 sqft',
        furnishtype: 'Unfurnished',
        mstatus: 'Status',
        movestatus: 'Ready to Move',
        flooroutof: '3 out of 4',
        washroom: 'Washroom',
        noofwashroom: 2,
        floor: 'Floor',
        nooffloor: '4',
        agent: 'Owner',
        buyers: '+ Buyers Served',
        buyerslist: 128,
        agentname: ' Ravi',
        pdetails: `Pent house is available for sale. It is fully furnished including 4 imported AC, fully loaded kitchen. `,
        cabtn: 'Contact Agent',
        pdbtn: `Property Detail's`,
        image: 'http://198.12.156.249:45001/pd/assets/images/propertylist/pg-6.jpg'
      },

      {
        pid: 12,
        ptype: 'residencial',
        routerLink: ['/features'],
        rupee: ` ₹`,
        persqftrs: '30625',
        persqft: 'per sqft',
        text1: `for sale in Vasant Vihar, New Delhi`,
        budget: '34 crore',
        bhk: '4 BHK',
        cotegory: 'Builder Floor',
        areatype: 'Super area',
        sqft: '8000 sqft',
        furnishtype: 'Unfurnished',
        mstatus: 'Status',
        movestatus: 'Ready to Move',
        flooroutof: 'Ground out of 4',
        washroom: 'Washroom',
        noofwashroom: 5,
        floor: 'Floor',
        nooffloor: '4',
        agent: 'Agent',
        buyers: '+ Buyers Served',
        buyerslist: 729,
        agentname: 'Miglani Enterprises',
        pdetails: `Luxurious Brand New Basement and Ground floor for sale in Vasant Vihar. `,
        cabtn: 'Contact Agent',
        pdbtn: `Property Detail's`,
        image: 'http://198.12.156.249:45001/pd/assets/images/propertylist/pg-7.jpg'
      },

      {
        pid: 13,
        ptype: 'residencial',
        routerLink: ['/features'],
        rupee: ` ₹`,
        persqftrs: '69136',
        persqft: 'per sqft',
        text1: `for Sale in Greater Kailash`,
        budget: '28 crore',
        text3: 'Baashyaam Constructions',
        bhk: '6 BHK',
        cotegory: 'House',
        areatype: 'Super area',
        sqft: '450 sqyrd',
        furnishtype: 'Unfurnished',
        mstatus: 'Status',
        movestatus: 'Ready to Move',
        flooroutof: '4 out of 5',
        washroom: 'Washroom',
        noofwashroom: 2,
        floor: 'Floor',
        nooffloor: '5',
        agent: 'Agent',
        buyers: '+ Buyers Served',
        buyerslist: 520,
        agentname: ' Sudarshan Sharma',
        pdetails: `Freehold Residential House built over 3 floors is a great deal to invest in.`,
        cabtn: 'Contact Agent',
        pdbtn: `Property Detail's`,
        image: 'http://198.12.156.249:45001/pd/assets/images/propertylist/pg-8.jpg'
      },

      {
        pid: 14,
        ptype: 'residencial',
        routerLink: ['/features'],
        rupee: ` ₹`,
        persqftrs: '125000',
        persqft: 'per sqft',
        text1: `for sale in Golf Links`,
        budget: '50 crore',
        bhk: '5 BHK',
        cotegory: 'House',
        areatype: 'Super area',
        sqft: '4000 sqft',
        furnishtype: 'Unfurnished',
        mstatus: 'Status',
        movestatus: 'Ready to Move',
        flooroutof: '6 out of 8',
        washroom: 'Washroom',
        noofwashroom: 3,
        floor: 'Floor',
        nooffloor: '8',
        agent: 'Agent',
        buyers: '+ Buyers Served',
        buyerslist: 920,
        agentname: ' Aman Bajaj',
        pdetails: `Freehold Residential House faces North direction & is made upto 1 floor. `,
        cabtn: 'Contact Agent',
        pdbtn: `Property Detail's`,
        image: 'http://198.12.156.249:45001/pd/assets/images/propertylist/pg-9.jpg'
      },
      {
        pid: 15,
        ptype: 'residencial',
        routerLink: ['/features'],
        rupee: ` ₹`,
        persqftrs: '168350',
        persqft: 'per sqft',
        text1: `for sale in DJA Apartments, Sector 13 Dwarka`,
        budget: '25 crore',
        bhk: '3 BHK',
        cotegory: 'Penthouse',
        areatype: 'Super area',
        sqft: '1485 sqft',
        furnishtype: 'Unfurnished',
        mstatus: 'Status',
        movestatus: 'Ready to Move',
        flooroutof: '3 out of 4',
        washroom: 'Washroom',
        noofwashroom: 2,
        floor: 'Floor',
        nooffloor: '4',
        agent: 'Owner',
        buyers: '+ Buyers Served',
        buyerslist: 128,
        agentname: ' Ravi',
        pdetails: `Pent house is available for sale. It is fully furnished including 4 imported AC, fully loaded kitchen. `,
        cabtn: 'Contact Agent',
        pdbtn: `Property Detail's`,
        image: 'http://198.12.156.249:45001/pd/assets/images/propertylist/pg-10.jpg'
      },

      {
        pid: 16,
        ptype: 'residencial',
        routerLink: ['/features'],
        rupee: ` ₹`,
        persqftrs: '30625',
        persqft: 'per sqft',
        text1: `for sale in Vasant Vihar, New Delhi`,
        budget: '34 crore',
        bhk: '4 BHK',
        cotegory: 'Builder Floor',
        areatype: 'Super area',
        sqft: '8000 sqft',
        furnishtype: 'Unfurnished',
        mstatus: 'Status',
        movestatus: 'Ready to Move',
        flooroutof: 'Ground out of 4',
        washroom: 'Washroom',
        noofwashroom: 5,
        floor: 'Floor',
        nooffloor: '4',
        agent: 'Agent',
        buyers: '+ Buyers Served',
        buyerslist: 729,
        agentname: 'Miglani Enterprises',
        pdetails: `Luxurious Brand New Basement and Ground floor for sale in Vasant Vihar. `,
        cabtn: 'Contact Agent',
        pdbtn: `Property Detail's`,
        image: 'http://198.12.156.249:45001/pd/assets/images/propertylist/pg-11.jpg'
      },
    ];
  }
  ngOnInit() {
  }
}
